name: ocr-app

services:
  fastapi:
    build: .
    container_name: fastapi
    volumes:
      - ./images:/images
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./images:/images
    depends_on:
      - fastapi
